application: thepizzabutton
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /pizza_list
  script: pizza_list.py

- url: /order_pizza*
  script: order_pizza.py

- url: /add_user*
  script: add_user.py

- url: /get_users
  script: get_users.py

- url: .*
  script: main.py
